name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat ebtables iptables git wget curl
          curl -LO https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install crictl
        run: |
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.31.0/crictl-v1.31.0-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-v1.31.0-linux-amd64.tar.gz
          sudo chmod +x /usr/local/bin/crictl
          rm -f crictl-v1.31.0-linux-amd64.tar.gz

      - name: Install cri-dockerd
        run: |
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          mkdir bin
          /usr/local/go/bin/go build -o cri-dockerd
          sudo cp cri-dockerd /usr/bin/
          cd ..
          rm -rf cri-dockerd

      - name: Install Container Networking Plugins
        run: |
          sudo mkdir -p /opt/cni/bin
          curl -LO https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
          sudo tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v1.1.1.tgz
          rm -f cni-plugins-linux-amd64-v1.1.1.tgz

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          eval $(minikube docker-env)

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest ./app

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/app-deployment

