name: CI/CD for Minikube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get remove -y containerd || true
          sudo apt-get update
          sudo apt-get install -y curl conntrack
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:latest -f app/Dockerfile .
          docker tag my-app:latest renancavalcantercb/my-app:latest
          docker push renancavalcantercb/my-app:latest

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Debug Kubernetes Resources
        run: |
          echo "Fetching Kubernetes resources for debugging..."
          kubectl get pods
          kubectl get deployments
          kubectl get services

      - name: Wait for Pods to be Ready
        run: |
          echo "Waiting for pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=my-app --timeout=600s

      - name: Debug Pods After Timeout
        if: failure()
        run: |
          echo "Debugging pods after timeout..."
          kubectl describe pod -l app=my-app
          kubectl logs -l app=my-app

      - name: Test Kubernetes Deployment
        run: |
          echo "Testing the service..."
          MINIKUBE_IP=$(minikube ip)
          NODE_PORT=$(kubectl get svc app-service -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "Service is available at http://$MINIKUBE_IP:$NODE_PORT"
          curl --fail "http://$MINIKUBE_IP:$NODE_PORT" || exit 1

