name: CI/CD for Kind

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl conntrack
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          curl -LO https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64
          chmod +x kind-linux-amd64
          sudo mv kind-linux-amd64 /usr/local/bin/kind

      - name: Create Kind Cluster
        run: |
          kind create cluster --name ci-cd-cluster

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Load Docker Image
        run: |
          docker build -t my-app:latest -f app/Dockerfile .
          kind load docker-image my-app:latest --name ci-cd-cluster

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for Pods to be Ready
        run: |
          echo "Waiting for pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=my-app --timeout=600s

      - name: Debug Kubernetes Resources
        run: |
          echo "Fetching Kubernetes resources for debugging..."
          kubectl get pods
          kubectl get deployments
          kubectl get services

      - name: Debug Pods Logs
        run: |
          echo "Fetching pod logs for debugging..."
          kubectl logs -l app=my-app

      - name: Debug Pods Description
        run: |
          echo "Fetching pod description for debugging..."
          kubectl describe pod -l app=my-app

      - name: Test Kubernetes Deployment
        run: |
          echo "Testing the service..."
          CLUSTER_IP=$(kubectl get svc app-service -o=jsonpath='{.spec.clusterIP}')
          echo "Service is available at http://$CLUSTER_IP:80"
          curl --fail "http://$CLUSTER_IP:80" || exit 1

