name: CI/CD for Minikube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io curl
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)
          docker build -t my-app:latest -f app/Dockerfile .

      - name: Load Docker Image into Minikube
        run: minikube image load my-app:latest

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Test Kubernetes Deployment
        run: |
          kubectl get all
          MINIKUBE_IP=$(minikube ip)
          NODE_PORT=$(kubectl get svc app-service -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "Service is available at http://$MINIKUBE_IP:$NODE_PORT"
          curl --fail "http://$MINIKUBE_IP:$NODE_PORT" || exit 1

